language: ruby
rvm:
  - 2.1.0
after_success:
  - cd _site
  - git init
  - git remote add deploy git@github.com:great-h/great-h.github.io.git
  - git add --all
  - 'git commit -m "Generate Travis JOB $TRAVIS_JOB_NUMBER

https://travis-ci.org/great-h/great-h.github.io/builds/$TRAVIS_BUILD_ID"'
  - '[ "x$TRAVIS_BRANCH" == "xsource" ] && git push -f deploy master'
branches:
  except:
    - master
env:
  global:
    - GIT_COMMITTER_NAME="Tomohiko Himura"
    - GIT_COMMITTER_EMAIL="eiel.hal@gmail.com"
    - GIT_AUTHOR_NAME="Tomohiko Himura"
    - GIT_AUTHOR_EMAIL="eiel.hal@gmail.com"
